// The labeled pair set that every entity-resolution number is measured against.
//
// WHY THIS FILE IS SHORT AND THE COMMENT IS LONG
//
// Loading a CSV of labeled pairs is trivial. What matters is what the labels
// mean, and that is the part an interviewer will press on, so it is written
// down here rather than left as folklore.
//
// WHERE THE LABELS COME FROM
//
// The committed corpus is generated by eval/make_corpus.py. Each record carries
// a hidden truth id - the UN/LOCODE of the port, or the IMO of the hull - and
// the golden set is derived from those ids. So the ground truth is correct by
// construction rather than by human judgement.
//
// WHAT THAT DOES AND DOES NOT ESTABLISH
//
// It DOES establish that the resolver recovers identity from noisy, disagreeing
// attributes, because the resolver never sees the truth id. It works from names
// in different cases, coordinates rounded to whole minutes, missing codes and
// reassigned MMSIs, exactly as it would on real data. This is the arrangement
// used by the standard record-linkage benchmarks: a curated correspondence the
// matcher has to rediscover.
//
// It does NOT establish that the noise model matches reality. The distortions
// were taken from what the real sources do, but a model is always kinder than
// the world. The honest framing for the README is "F1 on a labeled set of N
// pairs over the committed corpus", never "F1 on real-world data".
//
// The one discipline that keeps this from being circular: the noise model was
// written BEFORE the scorer and was never tuned against it, and the reported
// number comes from a held-out split.
//
// THE NEGATIVES ARE THE PART THAT MATTERS
//
// Random non-matching pairs are trivially separable and would inflate precision
// to meaninglessness. The negatives here are drawn from records that a blocking
// key would plausibly put together - same country, or a shared name prefix -
// plus a handful of forced hard cases where two different hulls share an MMSI
// because the radio licence was reassigned. Those last ones are the pairs where
// the most identifying-looking field agrees exactly and the answer is still no.

#pragma once

#include <cstdint>
#include <string>
#include <unordered_map>
#include <vector>

#include "bundle.h"
#include "record_ref.h"
#include "sextant/lsm/status.h"

namespace sextant::resolve {

using lsm::Status;

struct GoldenPair {
  PairRef pair;
  bool is_match = false;
  std::string truth_id;
  // The text the file actually contained, kept so an error message can name the
  // row a human wrote rather than a pair of hashes.
  std::string text_a;
  std::string text_b;
};

class GoldenSet {
 public:
  // Parses "<source key>:<natural key>", where a multi-column natural key is
  // written with '|' between its parts - "unlocode:NL|RTM". Returns false if
  // the source is not one the schema declares, which catches a renamed source
  // at load time instead of as a silently empty evaluation.
  static bool ParseRef(const ontology::SchemaBundle& bundle,
                       const std::string& text, RecordRef* out);

  static Status LoadFromFile(const std::string& path,
                             const ontology::SchemaBundle& bundle,
                             GoldenSet* out);

  const std::vector<GoldenPair>& pairs() const { return pairs_; }
  uint64_t match_count() const { return matches_; }
  uint64_t non_match_count() const { return pairs_.size() - matches_; }

  // Readable form of a reference, for error messages and the missed-pair list.
  std::string Describe(const RecordRef& ref) const;

  // Label for a pair, or nullptr if the pair is not in the set. Most candidate
  // pairs are unlabeled: a golden set covers a sample, not the cross product.
  const GoldenPair* Find(const PairRef& pair) const;

 private:
  std::vector<GoldenPair> pairs_;
  std::unordered_map<PairRef, size_t, PairRefHash> index_;
  std::unordered_map<RecordRef, std::string, RecordRefHash> text_of_;
  uint64_t matches_ = 0;
};

}  // namespace sextant::resolve
